version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=integradora2
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Permitir contraseñas vacías
      MYSQL_DATABASE: integradora2
      MYSQL_USER: root
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
